"""migrate

Revision ID: 848f91f61fef
Revises: 31f4f004812a
Create Date: 2017-03-17 16:48:44.976199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '848f91f61fef'
down_revision = '31f4f004812a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('registrations',
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('tags_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['tags_id'], ['tags.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registrations')
    op.drop_table('tags')
    # ### end Alembic commands ###
